defaults: &defaults
  adapter: postgresql
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 10
  timeout: 5000

development:
  <<: *defaults
  database:  hospital_scraper_development

test:
  <<: *defaults
  database:  hospital_scraper_test


production:
  <<: *defaults
  database:  hospital_scraper_production
